// <auto-generated />
using Catalog.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.DataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210414154320_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description for product 1",
                            Name = "Product 1",
                            Price = 6754m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description for product 2",
                            Name = "Product 2",
                            Price = 8117m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description for product 3",
                            Name = "Product 3",
                            Price = 9975m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description for product 4",
                            Name = "Product 4",
                            Price = 2227m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description for product 5",
                            Name = "Product 5",
                            Price = 7788m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description for product 6",
                            Name = "Product 6",
                            Price = 2635m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description for product 7",
                            Name = "Product 7",
                            Price = 7764m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description for product 8",
                            Name = "Product 8",
                            Price = 2508m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description for product 9",
                            Name = "Product 9",
                            Price = 3015m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description for product 10",
                            Name = "Product 10",
                            Price = 557m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description for product 11",
                            Name = "Product 11",
                            Price = 8011m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description for product 12",
                            Name = "Product 12",
                            Price = 8729m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description for product 13",
                            Name = "Product 13",
                            Price = 7704m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description for product 14",
                            Name = "Product 14",
                            Price = 4355m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description for product 15",
                            Name = "Product 15",
                            Price = 7340m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description for product 16",
                            Name = "Product 16",
                            Price = 1657m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description for product 17",
                            Name = "Product 17",
                            Price = 9406m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description for product 18",
                            Name = "Product 18",
                            Price = 9082m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description for product 19",
                            Name = "Product 19",
                            Price = 3278m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description for product 20",
                            Name = "Product 20",
                            Price = 3748m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description for product 21",
                            Name = "Product 21",
                            Price = 8188m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description for product 22",
                            Name = "Product 22",
                            Price = 5185m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description for product 23",
                            Name = "Product 23",
                            Price = 2658m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description for product 24",
                            Name = "Product 24",
                            Price = 2345m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description for product 25",
                            Name = "Product 25",
                            Price = 2644m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description for product 26",
                            Name = "Product 26",
                            Price = 3153m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description for product 27",
                            Name = "Product 27",
                            Price = 3163m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description for product 28",
                            Name = "Product 28",
                            Price = 7839m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description for product 29",
                            Name = "Product 29",
                            Price = 2672m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description for product 30",
                            Name = "Product 30",
                            Price = 1452m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description for product 31",
                            Name = "Product 31",
                            Price = 8136m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description for product 32",
                            Name = "Product 32",
                            Price = 9563m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description for product 33",
                            Name = "Product 33",
                            Price = 917m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description for product 34",
                            Name = "Product 34",
                            Price = 6491m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description for product 35",
                            Name = "Product 35",
                            Price = 3624m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description for product 36",
                            Name = "Product 36",
                            Price = 9936m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description for product 37",
                            Name = "Product 37",
                            Price = 6629m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description for product 38",
                            Name = "Product 38",
                            Price = 3922m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description for product 39",
                            Name = "Product 39",
                            Price = 2178m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description for product 40",
                            Name = "Product 40",
                            Price = 5641m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description for product 41",
                            Name = "Product 41",
                            Price = 3604m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description for product 42",
                            Name = "Product 42",
                            Price = 6084m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description for product 43",
                            Name = "Product 43",
                            Price = 4716m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description for product 44",
                            Name = "Product 44",
                            Price = 5899m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description for product 45",
                            Name = "Product 45",
                            Price = 9690m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description for product 46",
                            Name = "Product 46",
                            Price = 1093m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description for product 47",
                            Name = "Product 47",
                            Price = 139m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description for product 48",
                            Name = "Product 48",
                            Price = 4021m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description for product 49",
                            Name = "Product 49",
                            Price = 8423m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description for product 50",
                            Name = "Product 50",
                            Price = 4343m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description for product 51",
                            Name = "Product 51",
                            Price = 7466m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description for product 52",
                            Name = "Product 52",
                            Price = 7086m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description for product 53",
                            Name = "Product 53",
                            Price = 2684m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description for product 54",
                            Name = "Product 54",
                            Price = 8413m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description for product 55",
                            Name = "Product 55",
                            Price = 1045m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description for product 56",
                            Name = "Product 56",
                            Price = 1668m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description for product 57",
                            Name = "Product 57",
                            Price = 5558m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description for product 58",
                            Name = "Product 58",
                            Price = 7729m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description for product 59",
                            Name = "Product 59",
                            Price = 9583m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description for product 60",
                            Name = "Product 60",
                            Price = 4735m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description for product 61",
                            Name = "Product 61",
                            Price = 9471m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description for product 62",
                            Name = "Product 62",
                            Price = 9925m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description for product 63",
                            Name = "Product 63",
                            Price = 9835m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description for product 64",
                            Name = "Product 64",
                            Price = 1663m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description for product 65",
                            Name = "Product 65",
                            Price = 2420m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description for product 66",
                            Name = "Product 66",
                            Price = 8447m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description for product 67",
                            Name = "Product 67",
                            Price = 7911m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description for product 68",
                            Name = "Product 68",
                            Price = 1312m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description for product 69",
                            Name = "Product 69",
                            Price = 831m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description for product 70",
                            Name = "Product 70",
                            Price = 7403m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description for product 71",
                            Name = "Product 71",
                            Price = 5028m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description for product 72",
                            Name = "Product 72",
                            Price = 5583m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description for product 73",
                            Name = "Product 73",
                            Price = 7003m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description for product 74",
                            Name = "Product 74",
                            Price = 7637m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description for product 75",
                            Name = "Product 75",
                            Price = 244m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description for product 76",
                            Name = "Product 76",
                            Price = 2203m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description for product 77",
                            Name = "Product 77",
                            Price = 568m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description for product 78",
                            Name = "Product 78",
                            Price = 6759m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description for product 79",
                            Name = "Product 79",
                            Price = 2655m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description for product 80",
                            Name = "Product 80",
                            Price = 1650m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description for product 81",
                            Name = "Product 81",
                            Price = 3113m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description for product 82",
                            Name = "Product 82",
                            Price = 9141m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description for product 83",
                            Name = "Product 83",
                            Price = 9416m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description for product 84",
                            Name = "Product 84",
                            Price = 8329m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description for product 85",
                            Name = "Product 85",
                            Price = 3985m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description for product 86",
                            Name = "Product 86",
                            Price = 1150m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description for product 87",
                            Name = "Product 87",
                            Price = 6978m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description for product 88",
                            Name = "Product 88",
                            Price = 2504m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description for product 89",
                            Name = "Product 89",
                            Price = 5546m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description for product 90",
                            Name = "Product 90",
                            Price = 2055m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description for product 91",
                            Name = "Product 91",
                            Price = 4478m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description for product 92",
                            Name = "Product 92",
                            Price = 8899m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description for product 93",
                            Name = "Product 93",
                            Price = 4339m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description for product 94",
                            Name = "Product 94",
                            Price = 7443m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description for product 95",
                            Name = "Product 95",
                            Price = 6169m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description for product 96",
                            Name = "Product 96",
                            Price = 3678m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description for product 97",
                            Name = "Product 97",
                            Price = 6248m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description for product 98",
                            Name = "Product 98",
                            Price = 3153m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description for product 99",
                            Name = "Product 99",
                            Price = 3578m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description for product 100",
                            Name = "Product 100",
                            Price = 1342m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("StockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("StockId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            StockId = 1,
                            ProductId = 1,
                            Stock = 72
                        },
                        new
                        {
                            StockId = 2,
                            ProductId = 2,
                            Stock = 28
                        },
                        new
                        {
                            StockId = 3,
                            ProductId = 3,
                            Stock = 27
                        },
                        new
                        {
                            StockId = 4,
                            ProductId = 4,
                            Stock = 44
                        },
                        new
                        {
                            StockId = 5,
                            ProductId = 5,
                            Stock = 55
                        },
                        new
                        {
                            StockId = 6,
                            ProductId = 6,
                            Stock = 65
                        },
                        new
                        {
                            StockId = 7,
                            ProductId = 7,
                            Stock = 37
                        },
                        new
                        {
                            StockId = 8,
                            ProductId = 8,
                            Stock = 98
                        },
                        new
                        {
                            StockId = 9,
                            ProductId = 9,
                            Stock = 41
                        },
                        new
                        {
                            StockId = 10,
                            ProductId = 10,
                            Stock = 88
                        },
                        new
                        {
                            StockId = 11,
                            ProductId = 11,
                            Stock = 91
                        },
                        new
                        {
                            StockId = 12,
                            ProductId = 12,
                            Stock = 54
                        },
                        new
                        {
                            StockId = 13,
                            ProductId = 13,
                            Stock = 42
                        },
                        new
                        {
                            StockId = 14,
                            ProductId = 14,
                            Stock = 90
                        },
                        new
                        {
                            StockId = 15,
                            ProductId = 15,
                            Stock = 28
                        },
                        new
                        {
                            StockId = 16,
                            ProductId = 16,
                            Stock = 91
                        },
                        new
                        {
                            StockId = 17,
                            ProductId = 17,
                            Stock = 24
                        },
                        new
                        {
                            StockId = 18,
                            ProductId = 18,
                            Stock = 4
                        },
                        new
                        {
                            StockId = 19,
                            ProductId = 19,
                            Stock = 69
                        },
                        new
                        {
                            StockId = 20,
                            ProductId = 20,
                            Stock = 92
                        },
                        new
                        {
                            StockId = 21,
                            ProductId = 21,
                            Stock = 71
                        },
                        new
                        {
                            StockId = 22,
                            ProductId = 22,
                            Stock = 54
                        },
                        new
                        {
                            StockId = 23,
                            ProductId = 23,
                            Stock = 45
                        },
                        new
                        {
                            StockId = 24,
                            ProductId = 24,
                            Stock = 48
                        },
                        new
                        {
                            StockId = 25,
                            ProductId = 25,
                            Stock = 55
                        },
                        new
                        {
                            StockId = 26,
                            ProductId = 26,
                            Stock = 57
                        },
                        new
                        {
                            StockId = 27,
                            ProductId = 27,
                            Stock = 21
                        },
                        new
                        {
                            StockId = 28,
                            ProductId = 28,
                            Stock = 77
                        },
                        new
                        {
                            StockId = 29,
                            ProductId = 29,
                            Stock = 6
                        },
                        new
                        {
                            StockId = 30,
                            ProductId = 30,
                            Stock = 79
                        },
                        new
                        {
                            StockId = 31,
                            ProductId = 31,
                            Stock = 80
                        },
                        new
                        {
                            StockId = 32,
                            ProductId = 32,
                            Stock = 2
                        },
                        new
                        {
                            StockId = 33,
                            ProductId = 33,
                            Stock = 78
                        },
                        new
                        {
                            StockId = 34,
                            ProductId = 34,
                            Stock = 73
                        },
                        new
                        {
                            StockId = 35,
                            ProductId = 35,
                            Stock = 14
                        },
                        new
                        {
                            StockId = 36,
                            ProductId = 36,
                            Stock = 45
                        },
                        new
                        {
                            StockId = 37,
                            ProductId = 37,
                            Stock = 58
                        },
                        new
                        {
                            StockId = 38,
                            ProductId = 38,
                            Stock = 28
                        },
                        new
                        {
                            StockId = 39,
                            ProductId = 39,
                            Stock = 53
                        },
                        new
                        {
                            StockId = 40,
                            ProductId = 40,
                            Stock = 25
                        },
                        new
                        {
                            StockId = 41,
                            ProductId = 41,
                            Stock = 15
                        },
                        new
                        {
                            StockId = 42,
                            ProductId = 42,
                            Stock = 22
                        },
                        new
                        {
                            StockId = 43,
                            ProductId = 43,
                            Stock = 7
                        },
                        new
                        {
                            StockId = 44,
                            ProductId = 44,
                            Stock = 72
                        },
                        new
                        {
                            StockId = 45,
                            ProductId = 45,
                            Stock = 24
                        },
                        new
                        {
                            StockId = 46,
                            ProductId = 46,
                            Stock = 35
                        },
                        new
                        {
                            StockId = 47,
                            ProductId = 47,
                            Stock = 34
                        },
                        new
                        {
                            StockId = 48,
                            ProductId = 48,
                            Stock = 12
                        },
                        new
                        {
                            StockId = 49,
                            ProductId = 49,
                            Stock = 90
                        },
                        new
                        {
                            StockId = 50,
                            ProductId = 50,
                            Stock = 29
                        },
                        new
                        {
                            StockId = 51,
                            ProductId = 51,
                            Stock = 39
                        },
                        new
                        {
                            StockId = 52,
                            ProductId = 52,
                            Stock = 64
                        },
                        new
                        {
                            StockId = 53,
                            ProductId = 53,
                            Stock = 15
                        },
                        new
                        {
                            StockId = 54,
                            ProductId = 54,
                            Stock = 66
                        },
                        new
                        {
                            StockId = 55,
                            ProductId = 55,
                            Stock = 53
                        },
                        new
                        {
                            StockId = 56,
                            ProductId = 56,
                            Stock = 18
                        },
                        new
                        {
                            StockId = 57,
                            ProductId = 57,
                            Stock = 82
                        },
                        new
                        {
                            StockId = 58,
                            ProductId = 58,
                            Stock = 78
                        },
                        new
                        {
                            StockId = 59,
                            ProductId = 59,
                            Stock = 88
                        },
                        new
                        {
                            StockId = 60,
                            ProductId = 60,
                            Stock = 97
                        },
                        new
                        {
                            StockId = 61,
                            ProductId = 61,
                            Stock = 44
                        },
                        new
                        {
                            StockId = 62,
                            ProductId = 62,
                            Stock = 59
                        },
                        new
                        {
                            StockId = 63,
                            ProductId = 63,
                            Stock = 93
                        },
                        new
                        {
                            StockId = 64,
                            ProductId = 64,
                            Stock = 61
                        },
                        new
                        {
                            StockId = 65,
                            ProductId = 65,
                            Stock = 8
                        },
                        new
                        {
                            StockId = 66,
                            ProductId = 66,
                            Stock = 90
                        },
                        new
                        {
                            StockId = 67,
                            ProductId = 67,
                            Stock = 75
                        },
                        new
                        {
                            StockId = 68,
                            ProductId = 68,
                            Stock = 68
                        },
                        new
                        {
                            StockId = 69,
                            ProductId = 69,
                            Stock = 77
                        },
                        new
                        {
                            StockId = 70,
                            ProductId = 70,
                            Stock = 83
                        },
                        new
                        {
                            StockId = 71,
                            ProductId = 71,
                            Stock = 33
                        },
                        new
                        {
                            StockId = 72,
                            ProductId = 72,
                            Stock = 95
                        },
                        new
                        {
                            StockId = 73,
                            ProductId = 73,
                            Stock = 50
                        },
                        new
                        {
                            StockId = 74,
                            ProductId = 74,
                            Stock = 44
                        },
                        new
                        {
                            StockId = 75,
                            ProductId = 75,
                            Stock = 77
                        },
                        new
                        {
                            StockId = 76,
                            ProductId = 76,
                            Stock = 49
                        },
                        new
                        {
                            StockId = 77,
                            ProductId = 77,
                            Stock = 47
                        },
                        new
                        {
                            StockId = 78,
                            ProductId = 78,
                            Stock = 73
                        },
                        new
                        {
                            StockId = 79,
                            ProductId = 79,
                            Stock = 25
                        },
                        new
                        {
                            StockId = 80,
                            ProductId = 80,
                            Stock = 21
                        },
                        new
                        {
                            StockId = 81,
                            ProductId = 81,
                            Stock = 24
                        },
                        new
                        {
                            StockId = 82,
                            ProductId = 82,
                            Stock = 9
                        },
                        new
                        {
                            StockId = 83,
                            ProductId = 83,
                            Stock = 87
                        },
                        new
                        {
                            StockId = 84,
                            ProductId = 84,
                            Stock = 76
                        },
                        new
                        {
                            StockId = 85,
                            ProductId = 85,
                            Stock = 40
                        },
                        new
                        {
                            StockId = 86,
                            ProductId = 86,
                            Stock = 17
                        },
                        new
                        {
                            StockId = 87,
                            ProductId = 87,
                            Stock = 86
                        },
                        new
                        {
                            StockId = 88,
                            ProductId = 88,
                            Stock = 12
                        },
                        new
                        {
                            StockId = 89,
                            ProductId = 89,
                            Stock = 20
                        },
                        new
                        {
                            StockId = 90,
                            ProductId = 90,
                            Stock = 95
                        },
                        new
                        {
                            StockId = 91,
                            ProductId = 91,
                            Stock = 62
                        },
                        new
                        {
                            StockId = 92,
                            ProductId = 92,
                            Stock = 80
                        },
                        new
                        {
                            StockId = 93,
                            ProductId = 93,
                            Stock = 39
                        },
                        new
                        {
                            StockId = 94,
                            ProductId = 94,
                            Stock = 56
                        },
                        new
                        {
                            StockId = 95,
                            ProductId = 95,
                            Stock = 81
                        },
                        new
                        {
                            StockId = 96,
                            ProductId = 96,
                            Stock = 55
                        },
                        new
                        {
                            StockId = 97,
                            ProductId = 97,
                            Stock = 29
                        },
                        new
                        {
                            StockId = 98,
                            ProductId = 98,
                            Stock = 45
                        },
                        new
                        {
                            StockId = 99,
                            ProductId = 99,
                            Stock = 65
                        },
                        new
                        {
                            StockId = 100,
                            ProductId = 100,
                            Stock = 33
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Stock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.Stock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
