// <auto-generated />
using Catalog.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.DataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description for product 1",
                            Name = "Product 1",
                            Price = 3058m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description for product 2",
                            Name = "Product 2",
                            Price = 3278m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description for product 3",
                            Name = "Product 3",
                            Price = 8820m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description for product 4",
                            Name = "Product 4",
                            Price = 1544m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description for product 5",
                            Name = "Product 5",
                            Price = 4463m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description for product 6",
                            Name = "Product 6",
                            Price = 2401m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description for product 7",
                            Name = "Product 7",
                            Price = 434m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description for product 8",
                            Name = "Product 8",
                            Price = 5124m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description for product 9",
                            Name = "Product 9",
                            Price = 9574m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description for product 10",
                            Name = "Product 10",
                            Price = 6289m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description for product 11",
                            Name = "Product 11",
                            Price = 5206m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description for product 12",
                            Name = "Product 12",
                            Price = 5516m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description for product 13",
                            Name = "Product 13",
                            Price = 7683m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description for product 14",
                            Name = "Product 14",
                            Price = 4093m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description for product 15",
                            Name = "Product 15",
                            Price = 8621m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description for product 16",
                            Name = "Product 16",
                            Price = 6158m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description for product 17",
                            Name = "Product 17",
                            Price = 1981m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description for product 18",
                            Name = "Product 18",
                            Price = 2944m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description for product 19",
                            Name = "Product 19",
                            Price = 7072m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description for product 20",
                            Name = "Product 20",
                            Price = 3654m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description for product 21",
                            Name = "Product 21",
                            Price = 243m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description for product 22",
                            Name = "Product 22",
                            Price = 417m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description for product 23",
                            Name = "Product 23",
                            Price = 7268m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description for product 24",
                            Name = "Product 24",
                            Price = 8232m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description for product 25",
                            Name = "Product 25",
                            Price = 3926m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description for product 26",
                            Name = "Product 26",
                            Price = 5413m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description for product 27",
                            Name = "Product 27",
                            Price = 7059m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description for product 28",
                            Name = "Product 28",
                            Price = 5464m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description for product 29",
                            Name = "Product 29",
                            Price = 1548m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description for product 30",
                            Name = "Product 30",
                            Price = 3383m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description for product 31",
                            Name = "Product 31",
                            Price = 8825m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description for product 32",
                            Name = "Product 32",
                            Price = 4677m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description for product 33",
                            Name = "Product 33",
                            Price = 9687m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description for product 34",
                            Name = "Product 34",
                            Price = 8586m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description for product 35",
                            Name = "Product 35",
                            Price = 1260m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description for product 36",
                            Name = "Product 36",
                            Price = 9503m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description for product 37",
                            Name = "Product 37",
                            Price = 791m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description for product 38",
                            Name = "Product 38",
                            Price = 176m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description for product 39",
                            Name = "Product 39",
                            Price = 7023m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description for product 40",
                            Name = "Product 40",
                            Price = 6218m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description for product 41",
                            Name = "Product 41",
                            Price = 103m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description for product 42",
                            Name = "Product 42",
                            Price = 5218m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description for product 43",
                            Name = "Product 43",
                            Price = 8227m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description for product 44",
                            Name = "Product 44",
                            Price = 7407m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description for product 45",
                            Name = "Product 45",
                            Price = 8121m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description for product 46",
                            Name = "Product 46",
                            Price = 2367m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description for product 47",
                            Name = "Product 47",
                            Price = 5398m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description for product 48",
                            Name = "Product 48",
                            Price = 824m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description for product 49",
                            Name = "Product 49",
                            Price = 6448m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description for product 50",
                            Name = "Product 50",
                            Price = 6445m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description for product 51",
                            Name = "Product 51",
                            Price = 3643m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description for product 52",
                            Name = "Product 52",
                            Price = 2055m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description for product 53",
                            Name = "Product 53",
                            Price = 1535m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description for product 54",
                            Name = "Product 54",
                            Price = 9086m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description for product 55",
                            Name = "Product 55",
                            Price = 1223m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description for product 56",
                            Name = "Product 56",
                            Price = 2740m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description for product 57",
                            Name = "Product 57",
                            Price = 6009m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description for product 58",
                            Name = "Product 58",
                            Price = 688m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description for product 59",
                            Name = "Product 59",
                            Price = 7617m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description for product 60",
                            Name = "Product 60",
                            Price = 9049m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description for product 61",
                            Name = "Product 61",
                            Price = 5341m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description for product 62",
                            Name = "Product 62",
                            Price = 4970m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description for product 63",
                            Name = "Product 63",
                            Price = 3676m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description for product 64",
                            Name = "Product 64",
                            Price = 6290m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description for product 65",
                            Name = "Product 65",
                            Price = 7463m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description for product 66",
                            Name = "Product 66",
                            Price = 629m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description for product 67",
                            Name = "Product 67",
                            Price = 5829m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description for product 68",
                            Name = "Product 68",
                            Price = 9097m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description for product 69",
                            Name = "Product 69",
                            Price = 2933m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description for product 70",
                            Name = "Product 70",
                            Price = 9117m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description for product 71",
                            Name = "Product 71",
                            Price = 5466m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description for product 72",
                            Name = "Product 72",
                            Price = 1905m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description for product 73",
                            Name = "Product 73",
                            Price = 5921m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description for product 74",
                            Name = "Product 74",
                            Price = 953m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description for product 75",
                            Name = "Product 75",
                            Price = 3651m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description for product 76",
                            Name = "Product 76",
                            Price = 5025m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description for product 77",
                            Name = "Product 77",
                            Price = 2189m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description for product 78",
                            Name = "Product 78",
                            Price = 9860m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description for product 79",
                            Name = "Product 79",
                            Price = 210m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description for product 80",
                            Name = "Product 80",
                            Price = 1659m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description for product 81",
                            Name = "Product 81",
                            Price = 115m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description for product 82",
                            Name = "Product 82",
                            Price = 6335m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description for product 83",
                            Name = "Product 83",
                            Price = 9016m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description for product 84",
                            Name = "Product 84",
                            Price = 5102m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description for product 85",
                            Name = "Product 85",
                            Price = 9740m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description for product 86",
                            Name = "Product 86",
                            Price = 6870m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description for product 87",
                            Name = "Product 87",
                            Price = 3242m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description for product 88",
                            Name = "Product 88",
                            Price = 701m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description for product 89",
                            Name = "Product 89",
                            Price = 7462m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description for product 90",
                            Name = "Product 90",
                            Price = 8519m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description for product 91",
                            Name = "Product 91",
                            Price = 3594m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description for product 92",
                            Name = "Product 92",
                            Price = 203m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description for product 93",
                            Name = "Product 93",
                            Price = 2558m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description for product 94",
                            Name = "Product 94",
                            Price = 7973m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description for product 95",
                            Name = "Product 95",
                            Price = 976m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description for product 96",
                            Name = "Product 96",
                            Price = 5133m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description for product 97",
                            Name = "Product 97",
                            Price = 1641m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description for product 98",
                            Name = "Product 98",
                            Price = 2037m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description for product 99",
                            Name = "Product 99",
                            Price = 9944m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description for product 100",
                            Name = "Product 100",
                            Price = 7592m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("StockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("StockId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            StockId = 1,
                            Count = 61,
                            ProductId = 1
                        },
                        new
                        {
                            StockId = 2,
                            Count = 40,
                            ProductId = 2
                        },
                        new
                        {
                            StockId = 3,
                            Count = 43,
                            ProductId = 3
                        },
                        new
                        {
                            StockId = 4,
                            Count = 64,
                            ProductId = 4
                        },
                        new
                        {
                            StockId = 5,
                            Count = 44,
                            ProductId = 5
                        },
                        new
                        {
                            StockId = 6,
                            Count = 30,
                            ProductId = 6
                        },
                        new
                        {
                            StockId = 7,
                            Count = 50,
                            ProductId = 7
                        },
                        new
                        {
                            StockId = 8,
                            Count = 17,
                            ProductId = 8
                        },
                        new
                        {
                            StockId = 9,
                            Count = 23,
                            ProductId = 9
                        },
                        new
                        {
                            StockId = 10,
                            Count = 25,
                            ProductId = 10
                        },
                        new
                        {
                            StockId = 11,
                            Count = 18,
                            ProductId = 11
                        },
                        new
                        {
                            StockId = 12,
                            Count = 97,
                            ProductId = 12
                        },
                        new
                        {
                            StockId = 13,
                            Count = 14,
                            ProductId = 13
                        },
                        new
                        {
                            StockId = 14,
                            Count = 84,
                            ProductId = 14
                        },
                        new
                        {
                            StockId = 15,
                            Count = 69,
                            ProductId = 15
                        },
                        new
                        {
                            StockId = 16,
                            Count = 80,
                            ProductId = 16
                        },
                        new
                        {
                            StockId = 17,
                            Count = 94,
                            ProductId = 17
                        },
                        new
                        {
                            StockId = 18,
                            Count = 78,
                            ProductId = 18
                        },
                        new
                        {
                            StockId = 19,
                            Count = 40,
                            ProductId = 19
                        },
                        new
                        {
                            StockId = 20,
                            Count = 79,
                            ProductId = 20
                        },
                        new
                        {
                            StockId = 21,
                            Count = 56,
                            ProductId = 21
                        },
                        new
                        {
                            StockId = 22,
                            Count = 39,
                            ProductId = 22
                        },
                        new
                        {
                            StockId = 23,
                            Count = 25,
                            ProductId = 23
                        },
                        new
                        {
                            StockId = 24,
                            Count = 5,
                            ProductId = 24
                        },
                        new
                        {
                            StockId = 25,
                            Count = 98,
                            ProductId = 25
                        },
                        new
                        {
                            StockId = 26,
                            Count = 33,
                            ProductId = 26
                        },
                        new
                        {
                            StockId = 27,
                            Count = 38,
                            ProductId = 27
                        },
                        new
                        {
                            StockId = 28,
                            Count = 80,
                            ProductId = 28
                        },
                        new
                        {
                            StockId = 29,
                            Count = 1,
                            ProductId = 29
                        },
                        new
                        {
                            StockId = 30,
                            Count = 19,
                            ProductId = 30
                        },
                        new
                        {
                            StockId = 31,
                            Count = 51,
                            ProductId = 31
                        },
                        new
                        {
                            StockId = 32,
                            Count = 14,
                            ProductId = 32
                        },
                        new
                        {
                            StockId = 33,
                            Count = 52,
                            ProductId = 33
                        },
                        new
                        {
                            StockId = 34,
                            Count = 32,
                            ProductId = 34
                        },
                        new
                        {
                            StockId = 35,
                            Count = 83,
                            ProductId = 35
                        },
                        new
                        {
                            StockId = 36,
                            Count = 91,
                            ProductId = 36
                        },
                        new
                        {
                            StockId = 37,
                            Count = 68,
                            ProductId = 37
                        },
                        new
                        {
                            StockId = 38,
                            Count = 89,
                            ProductId = 38
                        },
                        new
                        {
                            StockId = 39,
                            Count = 29,
                            ProductId = 39
                        },
                        new
                        {
                            StockId = 40,
                            Count = 68,
                            ProductId = 40
                        },
                        new
                        {
                            StockId = 41,
                            Count = 58,
                            ProductId = 41
                        },
                        new
                        {
                            StockId = 42,
                            Count = 13,
                            ProductId = 42
                        },
                        new
                        {
                            StockId = 43,
                            Count = 89,
                            ProductId = 43
                        },
                        new
                        {
                            StockId = 44,
                            Count = 10,
                            ProductId = 44
                        },
                        new
                        {
                            StockId = 45,
                            Count = 10,
                            ProductId = 45
                        },
                        new
                        {
                            StockId = 46,
                            Count = 73,
                            ProductId = 46
                        },
                        new
                        {
                            StockId = 47,
                            Count = 91,
                            ProductId = 47
                        },
                        new
                        {
                            StockId = 48,
                            Count = 69,
                            ProductId = 48
                        },
                        new
                        {
                            StockId = 49,
                            Count = 62,
                            ProductId = 49
                        },
                        new
                        {
                            StockId = 50,
                            Count = 94,
                            ProductId = 50
                        },
                        new
                        {
                            StockId = 51,
                            Count = 95,
                            ProductId = 51
                        },
                        new
                        {
                            StockId = 52,
                            Count = 59,
                            ProductId = 52
                        },
                        new
                        {
                            StockId = 53,
                            Count = 97,
                            ProductId = 53
                        },
                        new
                        {
                            StockId = 54,
                            Count = 94,
                            ProductId = 54
                        },
                        new
                        {
                            StockId = 55,
                            Count = 62,
                            ProductId = 55
                        },
                        new
                        {
                            StockId = 56,
                            Count = 22,
                            ProductId = 56
                        },
                        new
                        {
                            StockId = 57,
                            Count = 16,
                            ProductId = 57
                        },
                        new
                        {
                            StockId = 58,
                            Count = 38,
                            ProductId = 58
                        },
                        new
                        {
                            StockId = 59,
                            Count = 66,
                            ProductId = 59
                        },
                        new
                        {
                            StockId = 60,
                            Count = 11,
                            ProductId = 60
                        },
                        new
                        {
                            StockId = 61,
                            Count = 91,
                            ProductId = 61
                        },
                        new
                        {
                            StockId = 62,
                            Count = 69,
                            ProductId = 62
                        },
                        new
                        {
                            StockId = 63,
                            Count = 17,
                            ProductId = 63
                        },
                        new
                        {
                            StockId = 64,
                            Count = 4,
                            ProductId = 64
                        },
                        new
                        {
                            StockId = 65,
                            Count = 73,
                            ProductId = 65
                        },
                        new
                        {
                            StockId = 66,
                            Count = 5,
                            ProductId = 66
                        },
                        new
                        {
                            StockId = 67,
                            Count = 45,
                            ProductId = 67
                        },
                        new
                        {
                            StockId = 68,
                            Count = 82,
                            ProductId = 68
                        },
                        new
                        {
                            StockId = 69,
                            Count = 2,
                            ProductId = 69
                        },
                        new
                        {
                            StockId = 70,
                            Count = 77,
                            ProductId = 70
                        },
                        new
                        {
                            StockId = 71,
                            Count = 13,
                            ProductId = 71
                        },
                        new
                        {
                            StockId = 72,
                            Count = 6,
                            ProductId = 72
                        },
                        new
                        {
                            StockId = 73,
                            Count = 49,
                            ProductId = 73
                        },
                        new
                        {
                            StockId = 74,
                            Count = 72,
                            ProductId = 74
                        },
                        new
                        {
                            StockId = 75,
                            Count = 21,
                            ProductId = 75
                        },
                        new
                        {
                            StockId = 76,
                            Count = 43,
                            ProductId = 76
                        },
                        new
                        {
                            StockId = 77,
                            Count = 49,
                            ProductId = 77
                        },
                        new
                        {
                            StockId = 78,
                            Count = 15,
                            ProductId = 78
                        },
                        new
                        {
                            StockId = 79,
                            Count = 94,
                            ProductId = 79
                        },
                        new
                        {
                            StockId = 80,
                            Count = 25,
                            ProductId = 80
                        },
                        new
                        {
                            StockId = 81,
                            Count = 41,
                            ProductId = 81
                        },
                        new
                        {
                            StockId = 82,
                            Count = 69,
                            ProductId = 82
                        },
                        new
                        {
                            StockId = 83,
                            Count = 18,
                            ProductId = 83
                        },
                        new
                        {
                            StockId = 84,
                            Count = 7,
                            ProductId = 84
                        },
                        new
                        {
                            StockId = 85,
                            Count = 24,
                            ProductId = 85
                        },
                        new
                        {
                            StockId = 86,
                            Count = 91,
                            ProductId = 86
                        },
                        new
                        {
                            StockId = 87,
                            Count = 16,
                            ProductId = 87
                        },
                        new
                        {
                            StockId = 88,
                            Count = 58,
                            ProductId = 88
                        },
                        new
                        {
                            StockId = 89,
                            Count = 70,
                            ProductId = 89
                        },
                        new
                        {
                            StockId = 90,
                            Count = 61,
                            ProductId = 90
                        },
                        new
                        {
                            StockId = 91,
                            Count = 76,
                            ProductId = 91
                        },
                        new
                        {
                            StockId = 92,
                            Count = 30,
                            ProductId = 92
                        },
                        new
                        {
                            StockId = 93,
                            Count = 24,
                            ProductId = 93
                        },
                        new
                        {
                            StockId = 94,
                            Count = 18,
                            ProductId = 94
                        },
                        new
                        {
                            StockId = 95,
                            Count = 76,
                            ProductId = 95
                        },
                        new
                        {
                            StockId = 96,
                            Count = 89,
                            ProductId = 96
                        },
                        new
                        {
                            StockId = 97,
                            Count = 96,
                            ProductId = 97
                        },
                        new
                        {
                            StockId = 98,
                            Count = 85,
                            ProductId = 98
                        },
                        new
                        {
                            StockId = 99,
                            Count = 36,
                            ProductId = 99
                        },
                        new
                        {
                            StockId = 100,
                            Count = 6,
                            ProductId = 100
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Stock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.Stock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
